<?php

return array (
  'name' => '优狐短视频矩阵系统',
  'categorytype' => 
  array (
    'default' => 'Default',
    'page' => 'Page',
    'article' => 'Article',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => 'Basic',
    'email' => 'Email',
    'dictionary' => 'Dictionary',
    'user' => 'User',
    'example' => 'Example',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '10000',
  'mail_smtp_pass' => 'password',
  'mail_verify_type' => '2',
  'mail_from' => '10000@qq.com',
  'fixedpage' => 'dashboard',
  'beian' => '湘ICP备2023008788号-1',
  'dianshu' => '1',
  'agent_ip' => '',
  'min_pay' => '11',
  'style_type' => '0',
  'login_image' => '/uploads/20211128/57bc9d0f57c317771d496a0c93fab9f5.jpg',
  'qiye_money' => '0.5',
  'shuiyin_money' => '0',
  'card_money' => '0.01',
  'juzhen_money' => '0.1',
  'jianji_money' => '0.05',
  'seo_money' => '0',
  'website_logo' => 'https://xinlian2023.oss-cn-shanghai.aliyuncs.com/202311/20/f33c42f33c860046b2fcb6fe4affaef2.png',
  'website_desc' => '优狐短视频矩阵系统为短视频智能运营提供一站式解决方案',
  'website_company' => '上海市优狐站互联网信息科技有限公司',
  'website_company_desc' => '上海市优狐站互联网信息科技有限公司',
  'website_company_address' => '上海市',
  'website_email' => 'dx920210@outlook.com',
  'website_qq' => '1515844536',
  'website_wechat' => '',
  'website_bg' => 'https://xinlian2023.oss-cn-shanghai.aliyuncs.com/202311/20/c7ab5f762d361e79474e095e98286c7e.jpg',
  'website_kehu' => '23500',
  'website_tdk_title' => '[官网]优狐短视频矩阵系统-互联网短视频一站式运营方案',
  'website_tdk_keyword' => '优狐短视频矩阵系统-互联网短视频一站式运营方案，短视频运营，企业号运营',
  'website_tdk_desc' => '优狐短视频矩阵系统-互联网短视频一站式运营方案，为互联网短视频一站式运营方案',
  'version' => '1.4',
  'agent_image' => '/assets/img/login_bg.jpg',
  'aliyun_bucket' => 'xinlian2023',
  'aliyun_keyid' => 'LTAI5tFKn6y8mr8Skf6sp4vF',
  'aliyun_secret' => 'XqqAWXcSFGxEm5PBu5FCGe9yFNk5Kl',
  'aliyun_cdn' => '',
  'paiming10_money' => '0',
  'paiming20_money' => '0',
  'ks_app_id' => 'ks657244072032457255',
  'ks_app_secret' => 'QskPjrLy4u_TQfBSh7d3ng',
  'ks_url' => 'https://111.230.38.185',
  'comment_money' => '0.05',
  'link_money' => '0',
  'juzhen_update_time' => '5',
  'im_money' => '0.05',
  'tandian_money' => '0',
  'video_update_max' => '50',
  'send_video_max' => '2',
  'pay_appid' => 'wx910018bdb56a419a',
  'pay_appkey' => '65d018202ae8a8473c29586ff1ae61e1',
  'wechat_name' => '新链智能科技',
  'wechat_select_result' => '',
  'bili_app_id' => '',
  'bili_app_secret' => '',
  'bili_url' => '',
  'open_tandian_data' => '1',
  'open_douyin_cookie' => '1',
  'open_realname' => '1',
  'baidu_keyid' => 'iLEHroVgHCQGtef91Ug2Mrho',
  'baidu_secret' => 'Mf3Z9zZlBnPTD0KlZVqiBKegI6r9QrTH',
  'open_douyin_open' => '1',
);
